------------------------
New Test: 18.4.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
peaks mistakenly found:
09:43:51 c:  0.7127106196158366
All events found (1)
------------------------
New Test: 10.6.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No Bursts AUSTRIA-UNIGRAZ  AUSTRIA

No false peaks found
Events not found (1/1):
 [[11:34:00, 1]]
------------------------
New Test: 11.7.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No Bursts AUSTRIA-UNIGRAZ  AUSTRIA

No false peaks found
Events not found (1/1):
 [[13:20:00, 1]]
------------------------
New Test: 2.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No false peaks found
All events found (1)
------------------------
New Test: 4.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No false peaks found
All events found (1)
------------------------
New Test: 6.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No false peaks found
All events found (2)
------------------------
New Test: 7.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No Bursts AUSTRIA-UNIGRAZ  AUSTRIA

No false peaks found
Events not found (3/3):
 [[09:53:00, 1], [10:15:00, 1], [12:55:00, 1]]
------------------------
New Test: 8.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
/home/lhoefig/.local/lib/python3.9/site-packages/pandas/core/series.py:872: UserWarnin     g: Warning: converting a masked element to nan.
  return np.asarray(self._values, dtype)
No false peaks found
Events not found (1/7):
 [[15:37:00, 1]]
------------------------
New Test: 9.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA
No Bursts AUSTRIA-UNIGRAZ  AUSTRIA

No false peaks found
Events not found (2/2):
 [[11:17:00, 1], [11:44:00, 1]]
------------------------
New Test: 27.9.2017
 starting download

Observatories: AUSTRIA-UNIGRAZ & AUSTRIA-OE3FLB
No Bursts AUSTRIA-UNIGRAZ  AUSTRIA-OE3FLB

No false peaks found
Events not found (1/1):
 [[12:10:00, 1]]
------------------------
New Test: 8.3.2017
 starting download

Traceback (most recent call last):
  File "/home/lhoefig/eCallistoRadioBursts/main.py", line 412, in <module>
    testBacBursts()
  File "/home/lhoefig/eCallistoRadioBursts/main.py", line 402, in testBacBursts
    print("Observatories: {} & {}".format(obs_[0], obs_[1]))
IndexError: list index out of range
